// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Batch_img_conv(arg1:string,arg2:string):Promise<Array<string>>;

export function Get_dir_path(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;
