// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Batch_img_conv(arg1, arg2) {
  return window['go']['main']['App']['Batch_img_conv'](arg1, arg2);
}

export function Get_dir_path(arg1) {
  return window['go']['main']['App']['Get_dir_path'](arg1);
}

export function Get_file_path(arg1) {
  return window['go']['main']['App']['Get_file_path'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Read_gforms_names(arg1, arg2) {
  return window['go']['main']['App']['Read_gforms_names'](arg1, arg2);
}

export function Read_verified_names(arg1, arg2) {
  return window['go']['main']['App']['Read_verified_names'](arg1, arg2);
}

export function Verify_names(arg1, arg2, arg3) {
  return window['go']['main']['App']['Verify_names'](arg1, arg2, arg3);
}
