// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {name_verification} from '../models';

export function Batch_img_conv(arg1:string,arg2:string):Promise<Array<string>>;

export function Get_dir_path(arg1:string):Promise<string>;

export function Get_file_path(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Read_gforms_names(arg1:string,arg2:number):Promise<Array<name_verification.CrimName>>;

export function Read_verified_names(arg1:string,arg2:number):Promise<Array<string>>;
